version: '3.7'
networks:
  JWT-network:
    internal: false
# volumes:
#   SymfonyMysqlVolume:
#     external: true
services:
  backend-symfony:
    image: action-learning-symfony
    depends_on:
      - mysql
    networks:
      - JWT-network
    ports:
      - target: 8081
        published: 84
        protocol: tcp
        mode: host
    environment:
      - APP_ENV=dev
      - APP_SECRET=thisisnotasecret
      - APP_DEBUG=true
      - DATABASE_URL=mysql://app_user:982hhfn9i24ugh925hg9235thrg39w28014t08hij@JWT-mysql:3306/JWT_db
    build:
      context: ./Symfony
      network: host
    volumes:
      - type: bind
        source: ./Symfony/app
        target: /var/www
  mysql:
    container_name: JWT-mysql
    networks:
      - JWT-network
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: Lift-extract-anthony-92
      MYSQL_DATABASE: JWT_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 982hhfn9i24ugh925hg9235thrg39w28014t08hij
    ports:
      - "3307:3306"
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./SymfonyMysqlVolume:/var/lib/mysql

  adminer:
    container_name: JWT-adminer
    networks:
      - JWT-network
    image: adminer
    ports:
      - "8082:8080"
