version: '3'
networks:
  php-network:
    internal: false
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-apache-php-app-usuarios
    volumes:
      - type: bind
        source: ./app/src
        target: /var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=Lift-extract-anthony-92
      - MYSQL_DATABASE=php
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=982hhfn9i24ugh925hg9235thrg39w28014t08hij
      - MYSQL_HOST=php-mysql-usuarios # Si cambio el nombre del container tambien el nombre del host
      - MYSQL_PORT=3306
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - php-network
  mysql:
    container_name: php-mysql-usuarios
    platform: linux/x86_64
    networks:
      - php-network
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: Lift-extract-anthony-92
      MYSQL_DATABASE: php
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 982hhfn9i24ugh925hg9235thrg39w28014t08hij
    ports:
      - "3307:3307"
    expose:
      - '3307'
    volumes:
      - ./PhpMysqlVolume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    container_name: adminer-usuarios
    networks:
      - php-network
    image: adminer
    ports:
      - "8081:8080"
